testing: use a project pool

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -25,8 +25,16 @@ cache:
 before_install:
 - if [ $SYSTEM_TESTS ]; then
     openssl aes-256-cbc -K $encrypted_e44ee91b46d4_key -iv $encrypted_e44ee91b46d4_iv -in key.json.enc -out key.json -d;
-    export GOLANG_SAMPLES_PROJECT_ID=golang-samples-tests;
     export GOOGLE_APPLICATION_CREDENTIALS="$(pwd)/key.json";
+
+    curl https://storage.googleapis.com/gimme-proj/linux_amd64/gimmeproj > gimmeproj && chmod +x gimmeproj;
+    ./gimmeproj version;
+    export GOLANG_SAMPLES_PROJECT_ID=$(./gimmeproj -project golang-samples-tests lease 12m);
+    if [ -z "$GOLANG_SAMPLES_PROJECT_ID" ]; then
+      echo "Lease failed.";
+      exit 1;
+    fi;
+    echo "Running tests in project $GOLANG_SAMPLES_PROJECT_ID";
   else
     echo "Not running system tests.";
   fi
@@ -54,3 +62,4 @@ install:
 
 script:
 - go test -v ./...
+- ./gimmeproj -project golang-samples-tests done $GOLANG_SAMPLES_PROJECT_ID
